### ISSUE TITLE
Implementar WooCommerce no lugar do S2Member

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#45]
Implementação do WooCommerce para venda e gestão de assinaturas no lugar do S2Member.

- [x] Configurar no Beta o WooCommerce
- [x] Solucionar migração de assinantes
- [x] Integração com sistema de pagamento
- [x] Validar tela de checkout
- [x] Validar tela de compra concluída
- [x] Refazer redirecionamento de home
- [ ] Tradução de termos em inglês (#59)
- [x] Migração de Posts para Categorias (#52)
- [ ] Revisão de páginas no ar (#53)
- [x] Logo Vetorizada
- [x] Definir como vai ser a migração (#54)
- [x] Migração de Membros pro novo sistema
- [x] Resolver bloqueio de telas de Buddypress+BBPress
- [x] Bloquear conteúdos para assinantes
- [x] Validar bloqueio de conteúdos
- [ ] Ok final e subir em produção (#55)

**Comment by gusfune** [comment]
@gustavogitti e @eduardoamuri podem dar uma conferida no que está no ar no momento no beta?

**Comment by eduardoamuri** [comment]
Comentários feitos na issue de migração do servidor.

**Comment by gusfune** [comment]
Pode colocar aqui os comentários referentes ao WooCommerce/Beta? Confundi tudo agora.

**Comment by eduardoamuri** [comment]
Sobre o WooCommerce:

O /carrinho parece estar funcionando, apesar de não conseguirmos resolver os testes por completo. A lista de estados não está sendo carregada corretamente (ele sempre puxa estados do EUA):

![screen shot 2017-03-01 at 9 33 17 am](https://cloud.githubusercontent.com/assets/247457/23461714/cccfc0d4-fe69-11e6-9964-82cf20e2a35d.png)

Consegui chegar quase até o final, quando ele me joga para o Paypal. Isso não vai mais existir quando implementarmos o checkout transparente, certo?

![screen shot 2017-03-01 at 9 36 10 am](https://cloud.githubusercontent.com/assets/247457/23461730/d24a386e-fe69-11e6-92d1-6ba15502b2e7.png)

Ó meu pedido, que bonitinho:

![screen shot 2017-03-01 at 9 37 24 am](https://cloud.githubusercontent.com/assets/247457/23461738/d8281116-fe69-11e6-854c-87c0a6edb2b4.png)

Adiantando, para você ir pensando na arquitetura por aí, não quereremos página de carrinho.

Como temos um produto só, e uma modalidade só, a ideia é cortar etapas. Da página principal o usuário vai para uma página onde ele já coloca todos os dados de cadastro e os dados de cartão, ai já assina de maneira recorrente.

Seguimos. :)

**Comment by eduardoamuri** [comment]
Ignore o erro do CEP, foi cagada minha. Os outros problemas são problemas, de fato. :)

**Comment by eduardoamuri** [comment]
Fala Gus, 

Por favor, me passa uma previsão de implementação do Woo+checkout transparente?

**Comment by gusfune** [comment]
Eu to voltando agora pro Brasil, amanhã retomo isso e fechamos. No meio tempo já está sendo feito o item #38 pra apresentar amanhã depois que chegar. Espero fecharmos tudo nessa semana.

**Comment by eduardoamuri** [comment]
Joia. :)

**Comment by gusfune** [comment]
@eduardoamuri, subi um update no beta.
No update integrei os campos de cadastro para compras no Brasil (corrigindo os bugs que apontou antes) e pulando o carrinho na hora de comprar.

**Novas Assinaturas**
Em https://beta.olugar.org/aberto/ é possível clicar no **Quero Participar** e ele vai direto pra página final de cadastro e compra. 
Preciso que verifique/valide.

**Integração com Pagamento**
Ta pendente ainda, to apanhando com os bugs do PayPal Developer nessa, mas to tendo alguns progressos, seria bom tentar liberar o Checkout Transparente pra me dar acesso as ferramentas deles e tentar integrar melhor.

**Checkout Transparente**
É necessário habilitar pra conta com a equipe do PayPal antes de poder testar.
Segue link para falar com eles: https://www.paypal.com/br/webapps/mpp/paypal-payments-pro

Avalia e me passa feedback desses itens pra seguirmos?

**Comment by eduardoamuri** [comment]
Gus, valeu!

Vamos lá:

**Novas assinaturas**
1) Tirar essas duas faixas:
![screen shot 2017-03-07 at 3 45 45 pm](https://cloud.githubusercontent.com/assets/247457/23672349/2c9ba0a4-034d-11e7-8b09-acd4764e86f4.png)

Trataremos as renovações na mão mesmo, por e-mail. Vamos simplificar tudo pra ficar bem bolo na cara. 

2) Retirar o campo "Informação adicional"

3) Retirar o box do paypal. Aqui entrarão os campos do cartão de crédito, certo? Ou um botão que leve para a página de pagamento. Acho ruim termos dois steps, a não ser que seja transacional (se o cara não faz o pagamento, apaga o usuário).

4) Traduzir tudo. 

5) Você consegue nos propor um layout bonitinho, com base nas alterações que pedi nos itens anteriores? Se não, vou pedir para algum amigo designer fazer.

**Integração com Pagamento**
Ok.

**Checkout Transparente**
Amanhã vou ao banco abrir a nova conta do lugar. Essa que está no ar é a do PdH. Peço em seguida.

**Comment by gusfune** [comment]
Respondendo item-a-item:

> 1. Tirar essas duas faixas.
Vendo aqui como tirar a do carrinho que é default do sistema.

> 2. Retirar o campo "Informação adicional"
Retirado.

> 3. Retirar o box do paypal. Aqui entrarão os campos do cartão de crédito, certo? Ou um botão que leve para a página de pagamento. Acho ruim termos dois steps, a não ser que seja transacional (se o cara não faz o pagamento, apaga o usuário).
Essa é a box padrão do WooCommerce pra método de pagamento. O checkout transparente eu to vendo como vamos poder implementar porquê acabei de ver que tem algumas restrições com o plugin de membership. Te passo detalhes mais pra frente assim que eu conseguir resolver a questão de implementar o PayPal básico.

> 4. Traduzir tudo.
Segurando isso pra descobrir o que ocorre que alguns itens não aparecem em português.

> 5. Você consegue nos propor um layout bonitinho, com base nas alterações que pedi nos itens anteriores? Se não, vou pedir para algum amigo designer fazer.
Isso no checkout? Estava usando o padrão do WooCommerce. Se for pra estilizar de outra forma eu preferiria receber isso pronto de designer pois os DAs aqui estão todos com pauta cheia.
Lembrando que a customização visual, especialmente dependendo do que for proposta, influencia nas horas de programação pra deixar de acordo.

Vamos seguindo aqui. Assim que retornar ao país eu foco mais detalhadamente nesses itens, integro paypal e também fico no aguardo do layout.

**Comment by eduardoamuri** [comment]
Gus,

Respondendo aqui: 

-- No checkout, ficará assim:
![screen shot 2017-03-08 at 11 29 29 am](https://cloud.githubusercontent.com/assets/247457/23707864/ab87765e-03f2-11e7-9b7f-435b645e6d0a.png)

Precisa de algo mais, além da conta do PayPal Plus? 

Pra mim, tanto faz a plataforma de pagamento, desde que o checkout seja transparente. 

Estou indo hoje ao banco resolver a questão da conta.

Obrigado.

**Comment by gusfune** [comment]
@eduardoamuri vamos a novidades:

## 1. Checkout Transparente
Temos duas formas de implementar com Stripe. A primeira é botando os dados na página:
<img width="942" alt="screenshot 2017-03-08 14 50 24" src="https://cloud.githubusercontent.com/assets/1147240/23716463/2c52cd4e-040f-11e7-8710-dc84d32fb713.png">

A segunda é pelo popup do Stripe na hora de clicar finalizar:
<img width="343" alt="screenshot 2017-03-08 14 51 12" src="https://cloud.githubusercontent.com/assets/1147240/23716484/35b7f076-040f-11e7-8ff4-5a5bbff6a1be.png">

Qual prefere?

## 2. Integração com Pagamento
Assim que tiver a conta do Stripe do lugar eu crio no lugar da conta da Epic que botei pra testes.

## 3. Layout do Checkout
Atualizado. Da uma olhada lá!

## 4. Funcionamento da Home
Encontrei o problema da home, era a lógica de redirecionamento do S2Member, já ajustei isso pra ficar compatível com ele e com o WooCommerce por hora (e depois quando tiver 100% migrado).

-
Avalia os itens e me retorna?

**Comment by eduardoamuri** [comment]
Tá ficando bonito, Gus!

1) Vamos de popup.

2) Funcionou! Vários detalhes de layout para matar, mas funcionou!

3) Aqui demorou pra aparecer com uma coluna só full width, mas aparece. Falta atualizar bastante coisa, né? Você viu os itens do print que eu postei? A gente mudou a ordem dos itens e o tamanho dos campos, dá uma olhada lá. É pra tirar os asteriscos vermelhos também. 

4) Ainda tá meio capenga, Gus. As vezes funciona, as vezes não. As vezes eu clico no "Quero entrar" e ele me joga pra página principal de novo.

Obs: Eu não acho ruim a ideia de tirar o s2member de vez (mantendo a conta de todos eles no paypal) 

Seguimos? 

Obrigado.

**Comment by eduardoamuri** [comment]
Bug extra, relacionado ao item 4 do comentário anterior: quando clico na fotinho do usuário que criei (depois de logar), ele dá 404.

**Comment by gusfune** [comment]
Certo @eduardoamuri, vamos lá por partes.
Do meu lado, anotado pra fazer:
- [ ] Implementar PopUp no pagamento do Stripe
- [ ] Inserir logo 128x128 no PopUp do Stripe
- [ ] Ajuste Layout: Ordem dos campos de acordo com a imagem
- [ ] Ajuste Layout: Ajustes visuais de tamanho dos campos
- [ ] Ajuste Layout: Retirar asteriscos
- [ ] Arrumar capenguice: Funcionamento do botão "quero entrar" na home
- [ ] Definir questão de acessos as áreas restritas
- [ ] Preparar espaço pra já implementar o WooCommerce no S2Member

**Comment by gusfune** [comment]
@eduardoamuri, to migrando o checklist pro primeiro post pois assim aparece no progresso do issues, ok? No caso os itens em aberto eu joguei pra lá. Vamos ao update.

## 1. Traduções
Os itens em inglês são do WooCommerce Subscriptions e do Membership, que a tradução oficial não existe, e a feita pela comunidade foi parcialmente feita.

Essa parte eu vou precisar de um help de vocês. Minha sugestão é traduzir direto no projeto público de tradução, pois ai fica disponível pra outras pessoas e não "quebra" em qualquer update do plugin.

https://translate.wordpress.com/projects/woocommerce/woocommerce-subscriptions/pt-br/default/
https://translate.wordpress.com/projects/woocommerce/woocommerce-memberships/pt-br/default/

Eu não sei qual dos dois plugins ta puxando os termos em inglês, então sugiro pra ganhar tempo traduzir os termos que identificarem em português.

Vale lembrar que além do checkout existe a seção de gerenciar a assinatura: https://beta.olugar.org/minha-conta/

## 2. Ajustar Categorias dos Posts
Vide issues #52 e #53 que cadastrei separadamente pra facilitar/organizar. Isso é essencial pra facilitar na hora de subirmos o WooCommerce em produção.

## 3. Campos de Checkout
Fiz todos os ajustes no checkout. Porém, o plugin de permitir o WooCommerce no Brasil torna o campo sexo obrigatório, mantive ele.
Retira-lo também vai criar uma confusão de realinhar os itens lado a lado. Verificar se ta bom como subi?

## 4. Logo Vetorizada
Me mandem a logo do Lugar vetorizada para fazer algumas customizações?

## 5. Bloquear e Validar conteúdo para assinantes
Finalizando quase todo o setup precisamos finalizar os ajustes referentes a conteúdos restritos para assinantes, coisa que ainda ta meio *capenga*. Isso depende do item 2 desse comentário pra seguir.

## 6. Migração S2Member->WooCommerce
Subi a issue #54 para discutirmos isso separadamente aqui por ser algo sensível.

Fico no aguardo do retorno. Me passa também feedback se faltam outros itens pra fechar.

**Comment by eduardoamuri** [comment]
**1. Traduções**
Ok, vamos trabalhar nisso. 

**2. Ajustar categorias**
Ok, vamos trabalhar nisso. 

**3. Campos de Checkout**
Alguns pontos:

3a) Essa mensagem está aparecendo, de maneira intermitente:
![screen shot 2017-03-10 at 11 17 00 am](https://cloud.githubusercontent.com/assets/247457/23798379/28a14250-0583-11e7-81b3-29129afbc778.png)

3b) Não precisamos dessa mensagem: "Crie uma conta preenchendo as informações abaixo. Se você já comprou conosco antes, faça o login no topo da página."

3c) Esta mensagem precisa ser mais curta, para caber em uma linha só: A senha deve ser de pelo menos sete caracteres. Para torná-la segura, é recomendado que use letras maiúsculas e minúsculas, números e símbolos como ! " ? $ % ^ & ).

Podemos reescrever para: A senha deve possuir ao menos sete caracteres. Utilize letras maiúsculas, minúsculas e números.

Podemos tirar a obrigatoriedade dos símbolos?

3d) Não precisamos desse box: 
![screen shot 2017-03-10 at 11 20 19 am](https://cloud.githubusercontent.com/assets/247457/23798474/95a5dc44-0583-11e7-841d-475f87a8d054.png)

3e) Em cima, ao invés de "Finalizar compra", vamos com "Faça seu cadastro". Não precisamos do subtítulo "Detalhes da cobrança" também. 

Para essa tela, é isso. 

**4) Logotipo vetorizável** 
[logo.zip](https://github.com/olugar/olugar/files/834173/logo.zip)

- - - 

Seguimos.

**Comment by gusfune** [comment]
@eduardoamuri já adiantando as coisas aqui:

> 3a) Essa mensagem está aparecendo, de maneira intermitente.

Isso ocorre quando já tem o produto no carrinho e vc tenta por de novo (pq o limite é uma assinatura). Eu vou alterar aqui pra tirar a mensagem pois se já estiver no carrinho já ta valendo.

> 3b) Não precisamos dessa mensagem: "Crie uma conta preenchendo as informações abaixo. Se você já comprou conosco antes, faça o login no topo da página."

Ok. Mas não acha bom ter alguma mensagem sobre a criação de conta?
E o usuário, o usuário precisa selecionar? Ta setado pra usar o email como padrão, preciso alterar.

> 3c) Esta mensagem precisa ser mais curta, para caber em uma linha só: A senha deve ser de pelo menos sete caracteres. Para torná-la segura, é recomendado que use letras maiúsculas e minúsculas, números e símbolos como ! " ? $ % ^ & ).

Sugere alguma coisa pra escrever? Me passa que coloco. Lembrando que dependendo da largura da tela vai invariavelmente quebrar a linha.

> 3e) Em cima, ao invés de "Finalizar compra", vamos com "Faça seu cadastro". Não precisamos do subtítulo "Detalhes da cobrança" também.

Ajustarei

–

To seguindo aqui, logo menos mando novidades pra fechar essa tela.

** TO DOS **
- [ ] Retirar mensagem de "não da pra por no carrinho"
- [ ] Retirar mensagem de criar conta.
- [ ] Alterar regra pra validação de senha
- [ ] Permitir cadastro com username no lugar de email
- [ ] Alterar mensagem de segurança de senha

**Comment by gusfune** [comment]
@eduardoamuri tenho update:

> 3c) Esta mensagem precisa ser mais curta, para caber em uma linha só: A senha deve ser de pelo menos sete caracteres. Para torná-la segura, é recomendado que use letras maiúsculas e minúsculas, números e símbolos como ! " ? $ % ^ & ).

Esse texto ta direto na tradução do WooCommerce e é exibido via JS. Alterar esse texto envolve ou mexer na tradução ou no JS, o que se perderia a cada update. A forma simples é: retirar essa mensagem at all. Pode ser?

> Podemos tirar a obrigatoriedade dos símbolos?

Não ta como obrigatório. O WooCommerce usa uma biblioteca de força de senha que mede a força da senha em níveis, que vai de 0 a 6. Hoje ele ta programado pra aceitar qualquer senha que tenha pelo menos nível 3, o que é bem razoável. Eu não recomendo mudar essa configuração, até pq 2 ele vai permitir muita coisa relativamente fácil de advinhar.

Restante dos itens está no ar, só preciso dos textos pra subir e matamos essa parte.

**Comment by eduardoamuri** [comment]
O texto estava no meu comentário, Gus. Pode retirar a mensagem at all. Ela aparece caso o cara entre com uma senha tosca, né? 

Vou validar todo o restante.

O lance da validação tá ok? Digo, dele não colocar os dados de cartão com cadastro errado (tava acontecendo isso com a validação de CPF).

**Comment by eduardoamuri** [comment]
Faltou retirar o quadrinho abaixo também: 

![screen shot 2017-03-10 at 1 14 30 pm](https://cloud.githubusercontent.com/assets/247457/23802894/8c8e6e40-0593-11e7-9039-4f7f709a05b7.png)

Tem um texto "texto customizado" que ficou perdido pela tela também hahaha :)

**Comment by eduardoamuri** [comment]
Hoje os campos "celular" e "estado" já entram em destaque vermelho, assim que a página carrega.

![screen shot 2017-03-10 at 1 26 10 pm](https://cloud.githubusercontent.com/assets/247457/23803509/89804f82-0595-11e7-956f-45884c136cb0.png)

**Comment by gusfune** [comment]
> Coloca o link para o add-to-cart no botão participe do cantinho superior da tela, por favor

Não entendi muito bem, o que precisa exatamente?

> Faltou retirar o quadrinho abaixo também.

Retirado. Só que tem um porém: em nenhum lugar até a página de pagamento tem claro qual o preço da mensalidade. Seria bom ver isso pq não é legal pra experiência de usuário.

Outra coisa: vc acha interessante tentarmos usar algum sistema de "conversão". Tem um plugin muito bom de WooCommerce que se o usuário chegou a por o email, mas não pagou, ele lista esses usuários e permite enviar email automatico.

> Questão do Usuário

Não achei nada pronto ou que fosse fácil permitir que a gente verifique o usuário antes do pagamento. Fiz um teste aqui e ele não cobra se não validar o usuário, o que não é um problema.

Minha sugestão é: hoje deixar assim, e já deixar no mapa arrumar outra forma de validar isso no futuro. Provavelmente isso até possa virar um plugin de WP pra vender ou publicar open-source, pois não tem NADA que faça isso. O grande problema é justamente o acesso ao banco de dados de usuário: se isso não for feito MUITO BEM, basicamente estamos entregando pra qualquer cara que saiba um pouco de JS e abrir o Console puxar TODA a lista de usuários (ou emails) do Lugar. Not cool. 

> Erro de adicionar ao carrinho.

Subi uma gambiarra mesmo pra isso. Esse erro só tem como acontecer se a pessoa clicou mais de uma vez pra ir comprar, então esperamos que seja raro precisar disso. Basicamente eu removo no load da página o erro, e se tem outros erros ele exibe por ser AJAX.

**Outros pontos**
De todos os pedidos que fez ai com o Stripe, vc chegou a testar se ta acessando corretamente as áreas fechadas? Verifica pra mim? To investigando pq os pagamentos feitos aparecem como processando e não concluido.

Vocês vão implementar alguma outra modalidade de pagamento do tipo trimestral, anual, etc? Isso seria bacana de testar.

**Comment by eduardoamuri** [comment]
Sobre o primeiro ponto, é esse botão aqui: 

![screen shot 2017-03-10 at 3 01 22 pm](https://cloud.githubusercontent.com/assets/247457/23806938/712662e8-05a2-11e7-937e-9266d45c11ae.png)

O botão participe tem que ir pra tela de checkout! 

> Outra coisa: vc acha interessante tentarmos usar algum sistema de "conversão". Tem um plugin muito bom de WooCommerce que se o usuário chegou a por o email, mas não pagou, ele lista esses usuários e permite enviar email automatico.

Acho massa, mas não pra agora.

> Minha sugestão é: hoje deixar assim,

Tudo ok. 

> Subi uma gambiarra mesmo pra isso. Esse erro só tem como acontecer se a pessoa clicou mais de uma vez pra ir comprar, então esperamos que seja raro precisar disso. Basicamente eu removo no load da página o erro, e se tem outros erros ele exibe por ser AJAX.

Gambiarra rocks.

> De todos os pedidos que fez ai com o Stripe, vc chegou a testar se ta acessando corretamente as áreas fechadas? Verifica pra mim? To investigando pq os pagamentos feitos aparecem como processando e não concluido.

Está tudo certinho. O único problema é: se o usuário não logado tenta acessar uma prática, ele cai na tela principal do lugar, quando na verdade deveria cair naquela tela marota de assinatura, sabe? Não a do checkout: 

![screen shot 2017-03-10 at 3 04 23 pm](https://cloud.githubusercontent.com/assets/247457/23807042/e4161fe6-05a2-11e7-9866-75b99dbc6a52.png)

Por enquanto, não teremos nenhuma tela de assinatura trimestral ou algo do tipo. Quem sabe mais pra frente.

**Comment by gusfune** [comment]
@eduardoamuri, ajustei todos os pontos que mencionou.
A validação do CPF eu fiz uns ajustes e a priori ele ta voltando quando tenta pagar no Stripe. Tentei desmontar a forma que foi feito, mas, seria tanta gambiarra que pode estragar o funcionamento das coisas.
Eu vou ver aqui se entro em contato direto com ele, qualquer coisa eu mesmo me proponho a subir o fix depois com calma.

**Comment by eduardoamuri** [comment]
Gus, 

Seguindo nossa novela por aqui.

** Sobre a tela de checkout **

Está ok, mesmo com o bug do CPF. Estou preocupado com o inglês. Se deixarmos o input dos dados do cartão na página, podemos traduzir, certo? 

** Sobre a tela de pós checkout **

Vamos ficar com uma tela bem mais simples que essa. 

Ajustes: 

- [ ] Não logar o usuário automaticamente ao efetuar o cadastro;
- [ ] Substituir todas as informações por um texto que ficará em uma page do Wordpress. É possível? Se não, nós te enviaremos um texto para colocar hardcoded já. O título da página será alterado para "Cadastro realizado"

Acho que é isso, hein? 

Vamo que vamo :)

**Comment by gusfune** [comment]
Vamos lá:

### Checkout
Os dados do cartão na página conseguimos traduzir, isso é ok.
Imagino que não deve demorar pro Stripe liberar o JS em português, vou entrar em contato com eles de qualquer forma pra ver quando sai isso do checkout no modal, não deve demorar. Eles disponibilizando é uma chave que viramos.

Mudei a configuração pra testar na página. Pode testar mais uma vez pra gente garantir que o checkout fecha 100%?

> Outra coisa importante: tem um bug chato no cadastro via mobile. É muito importante corrigirmos. O cursor fica perdido nos campos numéricos (CPF, data de nascimento, etc). Testa com qualquer celular que é fácil de ver.
O cursor do texto né? Na hora de digitar os números? Isso ta ligado ao plugin de máscaras do WooCommerce. Posso desabilitar, ou ainda, depois a gente tentar usar a própria máscara. Quer testar?

### Pós Checkout
É possível redirecionar pra uma página do WP sem problemas, já programei a base disso aqui, mas preciso que valide. Por hora botei em `https://beta.olugar.org/seja-bem-vindo/`, mas preciso que me passe qual a URL vai ser em prod pra não perder isso quando subir em prod.

A parte de não logar depois da compra é automático do Wordpress pra validar a conta do cara. Qual o problema de logar ele de cara? Isso pode dar problema? Se for acesso a menus, etc, a gente pode customizar a experiência na primeira página.

No aguardo aqui, vamos fechar em breve!

**Comment by eduardoamuri** [comment]
Gus, para fecharmos o checkout, preciso que você ajeite as máscaras mobile. Ai vamos para os testes finais.

**Comment by eduardoamuri** [comment]
Sobre o pos checkout, iremos para nossa prática de bem vindo: https://beta.olugar.org/pratica/bem-vindo/

**Comment by gusfune** [comment]
Ambos os itens no ar. Logo menos falamos pra alinhar o restante.

**Comment by gusfune** [comment]
Fechando essa issue pois está no ar. As melhorias pendentes seguimos separadamente.
